# Permite conexiones desde cualquier IP (no solo localhost)
listener 1883 
allow_anonymous true  # Opcional: Cambia a "false" si quieres autenticación

persistence true
persistence_location /mosquitto/data/

# Enviar logs a stdout (requiere `log_dest stdout` y `log_type all`)
log_dest stdout
log_type all

# Opcional: Autenticación
#password_file /mosquitto/config/passwd
